name: CMake Build and Test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**' 

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Install Google Test
      run: |
        git clone https://github.com/google/googletest.git
        cmake -S googletest -B build_googletest/googletest
        cmake --build build_googletest/googletest
        sudo cmake --install build_googletest/googletest

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Run tests
      run: |
        cd build
        ./TankGame
